### ISSUE TITLE
How to run developer mode to watch assets like scss, js?

### ISSUE THREAD

**Issue by jacoweb** [magesuite/theme-generator#2]
Hi!

When we have made a child theme, how to run developer mode to watch assets like scss, js?
Yarn build its for production, but we want to run it while developing.

need some input here :)

**Comment by krzksz** [comment]
Hello! You have two options available: `yarn watch` which just watches the files and rebuilds as needed and `yarn serve` which in addition opens the browsersync proxy that automatically reloads the page.

**Comment by jacoweb** [comment]
Thank you! Works perfect!
